export const LOGIN = "LOGIN" ;

export const REQUEST_AUTHENTICATION = "REQUEST_AUTHENTICATION";
export const AUTHENTICATION_REQUEST_SUCCESS = "AUTHENTICATION_REQUEST_SUCCESS";
export const AUTHENTICATION_REQUEST_FAIL = "AUTHENTICATION_REQUEST_FAIL ";


export const LOGOUT = "LOGOUT" ;